### ISSUE TITLE
Query: compilation time for unity_dynamic_Left_cxx.cxx.o

### ISSUE THREAD

**Issue by tylerjereddy** [kokkos/pykokkos-base#31]
I do see some notes in the `README` about slow compilation times, but I'm getting 1 hour, 48 minute build times for:

`python setup.py install -- -DENABLE_INTERNAL_KOKKOS=ON -DENABLE_LAYOUTS=ON -DENABLE_MEMORY_TRAITS=OFF -DKokkos_ARCH_PASCAL61=ON -DKokkos_ENABLE_OPENMP=ON -DKokkos_ENABLE_CUDA=ON -DBUILD_SHARED_LIBS=ON`

Mostly gets stuck here:

`[32/36] Building CXX object src/variants/CMakeFiles/libpykokkos-variants.dir/Unity/unity_dynamic_Left_cxx.cxx.o`

Is this normal? `ENABLE_MEMORY_TRAITS` is `OFF`, which is the main slow one mentioned in the docs. In general, this has been the hardest piece to install for me so far (Kokkos/pykokkos were not too bad). Working on Ubuntu Linux for now, which is the only "official" platform mentioned in `pykokkos` README.

**Comment by jrmadsen** [comment]
How much memory do you have on your machine? If you don’t have a lot then you are probably swapping which slows down the build even more. There is only so much that can be done about the compile times bc of the extensive use of templates in both Kokkos and pybind11

**Comment by tylerjereddy** [comment]
`free -h`

```
              total        used        free      shared  buff/cache   available
Mem:           125G        7.3G         84G        251M         33G        116G
Swap:           31G          0B         31G
```

**Comment by jrmadsen** [comment]
Plenty of memory. You might have really slow cores. You could try with CMAKE_UNITY_BUILD=OFF.

**Comment by tylerjereddy** [comment]
I think the cores are pretty fast too, maybe a little older now (see below), though still faster than a conventional compute node I think. Ok, perhaps I can try that flag next time. I'm hoping I don't have to rebuild often.

`lscpu`

```
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              20
On-line CPU(s) list: 0-19
Thread(s) per core:  2
Core(s) per socket:  10
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Core(TM) i9-7900X CPU @ 3.30GHz
Stepping:            4
CPU MHz:             1200.051
CPU max MHz:         4500.0000
CPU min MHz:         1200.0000
BogoMIPS:            6599.98
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
L3 cache:            14080K
NUMA node0 CPU(s):   0-19

```

**Comment by kaschau** [comment]
Just my two cents, but I find compiling kokkos separately and then pykokkos-base manually with cmake (limiting to -j 2-4 cores or so, regardless of memory or core count) is the fastest way to compile.  Kokkos compiles in seconds. And pykokkos-base in 5-10 mins or so. (I compile with similar flags to your example).

**Comment by tylerjereddy** [comment]
Ok, I could try, thanks. As a Python developer I was obviously looking for the convenience of `python -m pip install .`.

**Comment by jrmadsen** [comment]
https://github.com/kokkos/pykokkos-base/blob/main/.github/workflows/linux-ci.yml

Plenty of examples here using setup.py

**Comment by tylerjereddy** [comment]
`nvidia-smi` shows `Driver Version: 390.144`, which I think means I'll need `CUDA 9.1`. That's a bit older maybe--am I likely to encounter issues there?

I can build `pykokkos-base` now in reasonable time with CMake, but the cuda runtimes I've tested with so far had issues with my system cuda driver/library either not providing a symbol that was needed, or explicitly complaining about the driver being too old with `pytest` run in `pykokkos` via `Kokkos_Cuda_Instance.cpp:253` in Kokkos proper.

**Comment by tylerjereddy** [comment]
I can install a bit better now, though the process is still rather non-trivial, so I'll close this.
