### ISSUE TITLE
MAINT: python 3.11 support

### ISSUE THREAD

**Issue by tylerjereddy** [kokkos/pykokkos-base#44]
Python 3.11 RC1 is guaranteed to be ABI stable, so it is safe to start thinking/testing for compatibility there.

Currently, I see some `pybind11`-related failures like this during `pykokkos-base` build:

```
| [ 75%] Building CXX object CMakeFiles/libpykokkos-core.dir/Unity/unity_1_cxx.cxx.o
| In file included from /tmp/pykokkos-base/external/pybind11/include/pybind11/cast.h:16,
|                  from /tmp/pykokkos-base/external/pybind11/include/pybind11/attr.h:13,
|                  from /tmp/pykokkos-base/external/pybind11/include/pybind11/pybind11.h:45,
|                  from /tmp/pykokkos-base/include/common.hpp:54,
|                  from /tmp/pykokkos-base/include/traits.hpp:47,
|                  from /tmp/pykokkos-base/_skbuild/linux-x86_64-3.11/cmake-build/src/variants/views.cpp:3,
|                  from /tmp/pykokkos-base/_skbuild/linux-x86_64-3.11/cmake-build/CMakeFiles/libpykokkos-core.dir/Unity/unity_1_cxx.cxx:3:
| /tmp/pykokkos-base/external/pybind11/include/pybind11/detail/type_caster_base.h: In function ‘std::string pybind11::detail::error_string()’:
| /tmp/pykokkos-base/external/pybind11/include/pybind11/detail/type_caster_base.h:448:36: error: invalid use of incomplete type ‘PyFrameObject’ {aka ‘struct _frame’}
|   448 |                 "  " + handle(frame->f_code->co_filename).cast<std::string>() +
|       |                                
```

If you want to reproduce you can i.e., modify the `pykokkos` repo CI:

```diff
--- a/.github/workflows/main_ci.yml
+++ b/.github/workflows/main_ci.yml
@@ -13,7 +13,7 @@ jobs:
     strategy:
       matrix:
         platform: [ubuntu-latest]
-        python-version: ["3.8", "3.9", "3.10"]
+        python-version: ["3.11.0-rc.1"]
     runs-on: ${{ matrix.platform }}
     steps:
       - uses: actions/checkout@v3

```

and run `act -j test_pykokkos`

**Comment by jrmadsen** [comment]
$20 says that's fixed in 3.11.0-rc2. This has nothing to do with the ABI, it's a header include issue. They aren't going to break every package which uses pybind11 for that.

**Comment by tylerjereddy** [comment]
How old is `/tmp/pykokkos-base/external/pybind11` that gets vendored? 

My first bet would have been that `pybind11` would have shimmed around that by now. I'll try to check that later tonight. Most other large packages I've seen are already passing tests with `pybind11` + `3.11`, so it is a safe bet that we just need to bump `pybind11` I think.

**Comment by jrmadsen** [comment]
I think I just used whatever the current main or stable branch when I create the repo. No special changes, you probably just need to do a git pull inside the submodule. Looks like it was noted and fixed in Oct 2021: 

https://github.com/pybind/pybind11/issues/3367

https://github.com/pybind/pybind11/pull/3368

**Comment by tylerjereddy** [comment]
Looks all good with `3.11rc1` over in https://github.com/kokkos/pykokkos/pull/74 now. I'll leave this open as a reminder to update the submodule in this repo, then can remove the manual submodule update over there.

**Comment by tylerjereddy** [comment]
I guess we might want a single `3.11rc1` job in this repo as well? I'll try to help resolve the current CI issues here first though, before expanding more.
